#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

#set wallpaper
feh --bg-fill /home/sxnkr/wallpaper.sxnkr/desktop.wall/hunter.png &

## Configurations --------------------------------------------#

bspc monitor -d 1 2 3 4 5 6 7 8
#bspc monitor eDP-1 -d 1 2 3 4 5
#bspc monitor HDMI-1-0 -d 6 7 8 9

bspc config border_width         0.55
bspc config window_gap           12.5
bspc config split_ratio          0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config paddingless_monocle         true
bspc config single_monocle              false
bspc config focus_follows_pointer       true
bspc config remove_disable_monitors	true
bspc config merge_overlapping_monitors	true
## Window rules ----------------------------------------------#
# remove all rules first
bspc rule -r *:*
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a feh state=floating
bspc rule -a sxiv state=floating
bspc rule -a "alacritty -e cmus" desktop=^8 state=floating
bspc rule -a qBittorrent state=floating
bspc rule -a galculator state=floating
bspc rule -a zathura state=tiled
bspc rule -a Screenkey manage=off

#polybar
~/.config/polybar/launch.sh &
